### ISSUE TITLE
isolation = "process" doesn't include Predef

### ISSUE THREAD

**Issue by jjudd** [andyscott/rules_scala_annex#116]
Tried out the new isolation features for tests. Ran into the following error

```
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
	at org.specs2.runner.SbtRunner.tasks(SbtRunner.scala:27)
	at annex.SubprocessTestRunner$.$anonfun$main$3(SubprocessRunner.scala:31)
	at annex.SubprocessTestRunner$.$anonfun$main$3$adapted(SubprocessRunner.scala:30)
	at annex.TestFrameworkRunner$.withRunner(TestFrameworkRunner.scala:19)
	at annex.SubprocessTestRunner$.$anonfun$main$2(SubprocessRunner.scala:30)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
	at annex.ClassLoader$.withContextClassLoader(ClassLoader.scala:8)
	at annex.SubprocessTestRunner$.main(SubprocessRunner.scala:30)
	at annex.SubprocessTestRunner.main(SubprocessRunner.scala)
```

My guess is isn't being included in the new process. Will need to investigate more to find more info.

**Comment by pauldraper** [comment]
That's a classic Scala version error.

The runner is Scala 2.12, but the tests are Scala 2.11.

That should be correctly handled with classloaders; let me look.
